namespace: fullstack-prod

app:
  environment: prod

backend:
  replicas: 3
  imagePullPolicy: IfNotPresent

frontend:
  replicas: 3
  imagePullPolicy: IfNotPresent

ingress:
  enabled: true
  host: fullstack-cloud-platform.local