{{- if and .Values.externalSecrets.enabled (eq .Values.database.mode "external") }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: backend-database-external-secret
  namespace: {{ .Values.namespace }}

spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore

  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretName }}
        property: database_url

{{- end }}