{{- if and .Values.externalSecrets.enabled (eq .Values.database.mode "external") }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-database-external-secret
  namespace: {{ .Values.namespace | quote }}

spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | quote }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.database.secretName | quote }}
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: "{{ .Values.global.projectName }}/{{ .Values.app.environment }}/rds/postgres"
        property: database_url

{{- end }}