{{- if and .Values.externalSecrets.enabled (eq .Values.database.mode "external") }}

{{- $remoteSecretName := .Values.externalSecrets.remoteSecretName | default (printf "%s/%s/rds/postgres" .Values.global.projectName .Values.app.environment) }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-database-external-secret
  namespace: {{ .Values.namespace | quote }}

spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | quote }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.database.secretName | quote }}
    creationPolicy: Owner

  data:
    - secretKey: {{ .Values.database.urlKey | quote }}
      remoteRef:
        key: {{ $remoteSecretName | quote }}
        property: {{ .Values.externalSecrets.remoteSecretProperty | quote }}

{{- end }}