{{- if and .Values.externalSecrets.enabled (eq .Values.database.mode "external") }}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: {{ .Values.externalSecrets.secretStoreName | quote }}

spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName | quote }}
            namespace: {{ .Values.externalSecrets.serviceAccountNamespace | quote }}

{{- end }}