{{- if and .Values.externalSecrets.enabled (eq .Values.database.mode "external") }}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: {{ .Values.externalSecrets.secretStoreName | quote }}

spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.awsRegion | quote }}

      {{- if eq .Values.externalSecrets.authMode "secretRef" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.awsCredentialsSecretName | quote }}
            key: access-key
            namespace: {{ .Values.externalSecrets.serviceAccountNamespace | quote }}

          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.awsCredentialsSecretName | quote }}
            key: secret-access-key
            namespace: {{ .Values.externalSecrets.serviceAccountNamespace | quote }}

          sessionTokenSecretRef:
            name: {{ .Values.externalSecrets.awsCredentialsSecretName | quote }}
            key: session-token
            namespace: {{ .Values.externalSecrets.serviceAccountNamespace | quote }}

      {{- else }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName | quote }}
            namespace: {{ .Values.externalSecrets.serviceAccountNamespace | quote }}
      {{- end }}

{{- end }}