TASK_STATUS_OPEN = "open"
TASK_STATUS_IN_PROGRESS = "in_progress"
TASK_STATUS_DONE = "done"

TASK_STATUS_VALUES = (
    TASK_STATUS_OPEN,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_DONE,
)

TASK_TITLE_MAX_LENGTH = 200
TASK_STATUS_MAX_LENGTH = 50

DEFAULT_TASK_LIMIT = 50
MAX_TASK_LIMIT = 100
MIN_TASK_LIMIT = 1

DEFAULT_TASK_OFFSET = 0
MIN_TASK_OFFSET = 0

TASK_SEARCH_MAX_LENGTH = 100
TASK_SEARCH_MIN_LENGTH = 1
