namespace: fullstack-dev
global:
  awsAccountId: "859981975099"
  awsRegion: eu-central-1
app:
  environment: dev
database:
  mode: external
  secretName: backend-database-secret
  urlKey: DATABASE_URL
externalSecrets:
  enabled: true
  authMode: jwt
  refreshInterval: 1h
  secretStoreName: aws-secrets-manager
  awsCredentialsSecretName: awssm-secret
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets
  serviceAccountRoleArn: ""
  remoteSecretName: ""
  remoteSecretProperty: database_url
backend:
  replicas: 1
  strategy:
    maxUnavailable: 1
    maxSurge: 0
  image:
    tag: "021231a"
    pullPolicy: IfNotPresent
  config:
    sqlEcho: false
    dbInitRetries: 30
    dbInitRetryDelaySeconds: 1
  metrics:
    enabled: true
    path: /metrics
frontend:
  replicas: 1
  strategy:
    maxUnavailable: 1
    maxSurge: 0
  image:
    tag: "8a7d245"
    pullPolicy: IfNotPresent
ingress:
  enabled: true
  host: ""
