namespace: fullstack-prod

global:
  awsAccountId: "859981975099"
  awsRegion: eu-central-1

app:
  environment: prod

database:
  mode: external
  secretName: backend-database-secret
  urlKey: DATABASE_URL

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aws-secrets-manager
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets

backend:
  replicas: 3
  image:
    tag: main-latest
    pullPolicy: IfNotPresent

frontend:
  replicas: 3
  image:
    tag: main-latest
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: ""