namespace: fullstack-staging

global:
  awsAccountId: "859981975099"
  awsRegion: eu-central-1

app:
  environment: staging

database:
  mode: external
  secretName: backend-database-secret
  urlKey: DATABASE_URL

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aws-secrets-manager

backend:
  replicas: 2
  image:
    tag: staging-latest
    pullPolicy: IfNotPresent

frontend:
  replicas: 2
  image:
    tag: staging-latest
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: ""