namespace: fullstack-prod

global:
  projectName: fullstack-cloud-platform
  awsAccountId: "859981975099"
  awsRegion: eu-central-1

app:
  environment: prod

database:
  mode: external
  secretName: backend-database-secret
  urlKey: DATABASE_URL

backend:
  replicas: 3
  image:
    tag: main-latest
    pullPolicy: IfNotPresent

frontend:
  replicas: 3
  image:
    tag: main-latest
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: fullstack-cloud-platform.local