namespace: fullstack-local

global:
  projectName: fullstack-cloud-platform
  awsAccountId: ""
  awsRegion: eu-central-1
  imageRegistry: ""

app:
  version: "0.1.0"
  environment: local-k8s

database:
  mode: local
  secretName: backend-database-secret
  urlKey: DATABASE_URL

backend:
  name: backend
  replicas: 1
  port: 8000
  image:
    tag: latest
    pullPolicy: Never

frontend:
  name: frontend
  replicas: 1
  port: 80
  image:
    tag: latest
    pullPolicy: Never

postgres:
  image: postgres:16
  database: app
  username: app
  password: app
  port: 5432
  storageSize: 1Gi

ingress:
  enabled: true
  className: nginx
  host: localhost