namespace: fullstack-dev

global:
  awsAccountId: "859981975099"
  awsRegion: eu-central-1

app:
  environment: dev

database:
  mode: external
  secretName: backend-database-secret
  urlKey: DATABASE_URL

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreName: aws-secrets-manager
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets
  serviceAccountRoleArn: ""

backend:
  replicas: 1
  image:
    tag: develop-latest
    pullPolicy: IfNotPresent

frontend:
  replicas: 1
  image:
    tag: develop-latest
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: ""